import Head from "next/head";
import Footer from "../components/Footer";
import HeroSection from "../components/HeroSection";
import CompSection from "../components/sections/CompSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Navigation using nextjs and tailwindcss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <HeroSection />
      <CompSection />
      <Footer />
    </div>
  );
}
